baseURL = "https://youthful-villani-10bc56.netlify.com/"
languageCode = "en-us"
title = "EduBlog"
theme = ""
DefaultContentLanguage = "en"

[author]
  name = "Avi Mehenwal"
  homepage = "https://avimehenwal.in"

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1
  [languages.de]
    contentDir = "content/de"
    languageName = "Deutsch"
    weight = 2

[params]
disqus = "edublog" # disqus account name

[[params.socials]]
name = "About Me"
link = "https://avimehenwal.in"

[[params.socials]]
name = "Github"
link = "https://github.com/avimehenwal"

[taxonomies]
  category = "categories"
  series   = "series"
  tag      = "tags"
