---
title       : "Markdown using Blackfriday Go Parser"
date        : 2019-02-18T10:12:02+01:00
video       : ""
categories  : ["myLearning"]
series      : ["development"]
tags        : ["markdown", "asciidoctor", "hugo"]
revision    : 0
---

:icons: font

An admonition paragraph draws the reader's attention to
auxiliary information.
Its purpose is determined by the label
at the beginning of the paragraph.

Here are the other built-in admonition types:

NOTE: Asciidoctor supports font-based admonition icons, powered by Font Awesome!

TIP: Pro tip...

IMPORTANT: Don't forget...

WARNING: Watch out for...

CAUTION: Ensure that...


Ever wondered *why* or *which* markdown parser to use for your blog publication?
Why even bother about it?

icon:comment[]

icon:heart[]

icon:exclamation-circle[]

icon:info-circle[]

Well,  it turns out to be that markdown can save you some time while writing big blogs posts (>500 words).
Markdown really shines when you have long posts and do not want to hassle with HTML close and open tags placements.
And most of the **.md** file looks like a plain redablle _text_ file, except with some markdown directives which
add HTML tags around text for final presentation to the browser.

=== How do I format text with blackfriday?

Terms and Definition List

    word
    : definition

{{< highlight html "style=friendly,linenos=table" >}}
HTML generated by blackfriday
<dl>
    <dt>word</dt>
    <dd>definition</dd>
</dl>
{{< /highlight >}}

Final result will look something like this on browser :smile:

word
: definition

Tasl list

- [x] Write the press release
- [ ] Update the website
- [ ] Contact the media

Linking to headlines

[Heading IDs](#heading-ids)

#### Open questions
How to highlight a text in markdown?

<mark>some text</mark>

==marked==

Add latex to markdown

https://gohugo.io/content-management/formats/#mathjax-with-hugo

### Alterbatives
asciidoctor
: could be used as an external tool

### Crossreference
Use relative references as they works better when testing development versions

```
< relref "document.md#anchor" >
< relref path="document.md" lang="ja" >
```

asciidoctor
If you want to reference a block element, all you need to do is assign an ID to that block.
You can enclose the ID in double square brackets:

Asciidoctor provides three strategies for display icons: as text, as images or as a
characters selected from an icon font. The strategy is controlled using the icons attribute.
The default behavior is to display the fallback text.

Adding font awesome icons to asciidoc documents
https://github.com/asciidoctor/asciidoctor-stylesheet-factory

icon:heart[size=2x]

icon:icon-note[size=2x]

[NOTE]
====
An admonition block may contain complex content.

.A list
- one
- two
- three

Another paragraph.
====

Refer to <<Internal Cross References>>.

normal Markdown syntax
Refer to <<Internal Cross References>>.

#### How to configure blackfriday from hugo

``` bash {.line-numbers}
blackfriday:
  angledQuotes: true
  extensions:
  - hardLineBreak
  fractions: false
  plainIDAnchors: true
```

:toc:

[bibliography]
=== References
* https://github.com/russross/blackfriday
* https://gohugo.io/getting-started/configuration/#configure-blackfriday
* https://stackoverflow.com/questions/25104738/text-highlight-in-markdown
* https://powerman.name/doc/asciidoc
* https://en.wikipedia.org/wiki/Lightweight_markup_language
* https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/_includes/icons.adoc



This is a footnote.[^1]

[^1]: the footnote text.
